/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

/**
 *
 * @author Israel Sales
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrameBemVindo = new javax.swing.JInternalFrame();
        jPanelInterno = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButtonCadastroMedico = new javax.swing.JButton();
        jButtonCadastroEnfermeira = new javax.swing.JButton();
        jButtonCadastroPaciente = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabelPainelFundo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButtonFecharTelaBemVindo = new javax.swing.JButton();
        jLabelFundoPrincipal = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuCadastros = new javax.swing.JMenu();
        jMenuItemCadastrosMedicos = new javax.swing.JMenuItem();
        jMenuItemCadastrosPacientes = new javax.swing.JMenuItem();
        jMenuItemCadastrosEnfermeiros = new javax.swing.JMenuItem();
        jMenuItemCadastrosUsuarios = new javax.swing.JMenuItem();
        jMenuRelatorios = new javax.swing.JMenu();
        jMenuFerramentas = new javax.swing.JMenu();
        jMenuItemFerramentasTelaBemVindos = new javax.swing.JMenuItem();
        jMenuSair = new javax.swing.JMenu();
        jMenuItemSairSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jInternalFrameBemVindo.setTitle("Bem-Vindo");
        jInternalFrameBemVindo.setVisible(true);
        jInternalFrameBemVindo.getContentPane().setLayout(null);

        jPanelInterno.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelInterno.setLayout(null);

        jLabel2.setText("Cadastros -");
        jPanelInterno.add(jLabel2);
        jLabel2.setBounds(10, 0, 60, 20);

        jButtonCadastroMedico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/CadMedicos.png"))); // NOI18N
        jButtonCadastroMedico.setToolTipText("Médico");
        jPanelInterno.add(jButtonCadastroMedico);
        jButtonCadastroMedico.setBounds(10, 20, 120, 140);

        jButtonCadastroEnfermeira.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon-infermeira.png"))); // NOI18N
        jButtonCadastroEnfermeira.setToolTipText("Enfermeiras");
        jButtonCadastroEnfermeira.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastroEnfermeiraActionPerformed(evt);
            }
        });
        jPanelInterno.add(jButtonCadastroEnfermeira);
        jButtonCadastroEnfermeira.setBounds(140, 20, 120, 140);

        jButtonCadastroPaciente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cadPacientes.png"))); // NOI18N
        jButtonCadastroPaciente.setToolTipText("Pacientes");
        jButtonCadastroPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastroPacienteActionPerformed(evt);
            }
        });
        jPanelInterno.add(jButtonCadastroPaciente);
        jButtonCadastroPaciente.setBounds(280, 20, 130, 140);

        jLabel3.setText("Agenda -");
        jPanelInterno.add(jLabel3);
        jLabel3.setBounds(10, 170, 60, 14);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Agenda.png"))); // NOI18N
        jButton1.setToolTipText("Agendamento");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanelInterno.add(jButton1);
        jButton1.setBounds(10, 190, 110, 110);

        jLabelPainelFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/internalframe.png"))); // NOI18N
        jPanelInterno.add(jLabelPainelFundo);
        jLabelPainelFundo.setBounds(0, 0, 1030, 310);

        jInternalFrameBemVindo.getContentPane().add(jPanelInterno);
        jPanelInterno.setBounds(0, 60, 1030, 310);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Sistema de gerenciamento de:");
        jInternalFrameBemVindo.getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 20, 290, 30);

        jButtonFecharTelaBemVindo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/exit.png"))); // NOI18N
        jButtonFecharTelaBemVindo.setToolTipText("Fechar Tela Bem-Vindo");
        jButtonFecharTelaBemVindo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFecharTelaBemVindoActionPerformed(evt);
            }
        });
        jInternalFrameBemVindo.getContentPane().add(jButtonFecharTelaBemVindo);
        jButtonFecharTelaBemVindo.setBounds(980, 0, 40, 40);

        getContentPane().add(jInternalFrameBemVindo);
        jInternalFrameBemVindo.setBounds(0, 80, 1040, 400);

        jLabelFundoPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundo_telaprincipal.jpg"))); // NOI18N
        getContentPane().add(jLabelFundoPrincipal);
        jLabelFundoPrincipal.setBounds(0, 0, 1040, 470);

        jMenuCadastros.setText("Cadastros");

        jMenuItemCadastrosMedicos.setText("Médicos");
        jMenuItemCadastrosMedicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadastrosMedicosActionPerformed(evt);
            }
        });
        jMenuCadastros.add(jMenuItemCadastrosMedicos);

        jMenuItemCadastrosPacientes.setText("Pacientes");
        jMenuCadastros.add(jMenuItemCadastrosPacientes);

        jMenuItemCadastrosEnfermeiros.setText("Enfermeiros");
        jMenuCadastros.add(jMenuItemCadastrosEnfermeiros);

        jMenuItemCadastrosUsuarios.setText("Usuários");
        jMenuCadastros.add(jMenuItemCadastrosUsuarios);

        jMenuBar1.add(jMenuCadastros);

        jMenuRelatorios.setText("Relatórios");
        jMenuBar1.add(jMenuRelatorios);

        jMenuFerramentas.setText("Ferramentas");

        jMenuItemFerramentasTelaBemVindos.setText("Tela Bem-Vindos");
        jMenuItemFerramentasTelaBemVindos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemFerramentasTelaBemVindosActionPerformed(evt);
            }
        });
        jMenuFerramentas.add(jMenuItemFerramentasTelaBemVindos);

        jMenuBar1.add(jMenuFerramentas);

        jMenuSair.setText("Sair");

        jMenuItemSairSair.setText("Sair");
        jMenuItemSairSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSairSairActionPerformed(evt);
            }
        });
        jMenuSair.add(jMenuItemSairSair);

        jMenuBar1.add(jMenuSair);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(1055, 535));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemCadastrosMedicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadastrosMedicosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemCadastrosMedicosActionPerformed

    private void jButtonCadastroEnfermeiraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastroEnfermeiraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCadastroEnfermeiraActionPerformed

    private void jButtonCadastroPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastroPacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCadastroPacienteActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonFecharTelaBemVindoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFecharTelaBemVindoActionPerformed
        jInternalFrameBemVindo.dispose();

    }//GEN-LAST:event_jButtonFecharTelaBemVindoActionPerformed

    private void jMenuItemSairSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSairSairActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItemSairSairActionPerformed

    private void jMenuItemFerramentasTelaBemVindosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemFerramentasTelaBemVindosActionPerformed
        // TODO add your handling code here:
        jInternalFrameBemVindo.setVisible(true);
    }//GEN-LAST:event_jMenuItemFerramentasTelaBemVindosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonCadastroEnfermeira;
    private javax.swing.JButton jButtonCadastroMedico;
    private javax.swing.JButton jButtonCadastroPaciente;
    private javax.swing.JButton jButtonFecharTelaBemVindo;
    private javax.swing.JInternalFrame jInternalFrameBemVindo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelFundoPrincipal;
    private javax.swing.JLabel jLabelPainelFundo;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuCadastros;
    private javax.swing.JMenu jMenuFerramentas;
    private javax.swing.JMenuItem jMenuItemCadastrosEnfermeiros;
    private javax.swing.JMenuItem jMenuItemCadastrosMedicos;
    private javax.swing.JMenuItem jMenuItemCadastrosPacientes;
    private javax.swing.JMenuItem jMenuItemCadastrosUsuarios;
    private javax.swing.JMenuItem jMenuItemFerramentasTelaBemVindos;
    private javax.swing.JMenuItem jMenuItemSairSair;
    private javax.swing.JMenu jMenuRelatorios;
    private javax.swing.JMenu jMenuSair;
    private javax.swing.JPanel jPanelInterno;
    // End of variables declaration//GEN-END:variables
}
